name: login
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  curved_navigation_bar: ^1.0.3
  smooth_page_indicator: ^1.0.1
  animated_text_kit: ^4.2.2
  awesome_snackbar_content: ^0.1.3
  flutter_slidable: ^3.0.0
  animated_bottom_navigation_bar: ^1.2.0
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  firebase_storage: ^11.1.2
  fluttertoast: ^8.0.9
  google_nav_bar: ^5.0.6
  path_provider: ^2.0.14
  cloud_firestore: ^4.5.0
  firebase_messaging: ^14.4.1
  flutter_local_notifications: ^14.0.0+1
  firebase_database: ^10.1.1
  modal_progress_hud_nsn: ^0.3.0
  blurry_modal_progress_hud: ^1.1.0
  http: ^0.13.6
  url_launcher: ^6.1.11
  clipboard: ^0.1.3
  convert: ^3.1.1
  simple_gradient_text: ^1.2.4
  flutter_svg: ^2.0.5


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - icon/

  fonts:
    - family: Fasthand
      fonts:
        - asset: fonts/Fasthand-Regular.ttf

    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf

    - family: Gothvetica
      fonts:
        - asset : fonts/Gothvetica-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf

    - family: SF Pro
      fonts:
        - asset: fonts/SF-Pro-Regular.ttf

    - family: Newyork
      fonts:
        - asset: fonts/NewYork.ttf

    - family: SF-Compact
      fonts:
        - asset: fonts/SF-Compact-Display-Medium.otf

    - family: Cinzel
      fonts:
        - asset: fonts/Cinzel-Regular.ttf
